# Change 'comments' to true for Disqus comments

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-ID: 'xxxx'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Posts', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/switchfootsid'}
- {icon: 'twitter', link: 'https://twitter.com/siddkotwal'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/siddharth-kotwal-32454235/'}
- {icon: 'envelope', link: 'mailto:siddharth481@gmail.com'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Related Posts'

post_date_prefix: 'Written on'
